export { default } from './ui/icon'
export * from './ui/icon'

export * from './variants/close'
export * from './variants/chevron-right'
export * from './variants/dots'
export * from './variants/eye-off'
export * from './variants/eye'
export * from './variants/logo'
export * from './variants/logout'
export * from './variants/plus'
export * from './variants/trash'
export * from './variants/user'
export * from './variants/search'
