export type EventNames =
  | 'setScale'
  | 'setTranslate'
  | 'setPosition'
  | 'setItemStates'
  | 'setSelected'
  | 'setRuleList'
  | 'setItemState'
  | 'setPaintingPanelRef'
  | 'setCanvasBoardRef'
  | 'setEditingLink'
